name: 'Close Stale Issues'
description: 'Close issues and pull requests with no recent activity'
author: 'GitHub'
inputs:
  repo-token:
    description: 'Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: true
  stale-issue-message:
    description: 'The message to post on the issue when tagging it. If none provided, will not mark issues stale.'
  stale-pr-message:
    description: 'The message to post on the pr when tagging it. If none provided, will not mark pull requests stale.'
  days-before-stale:
    description: 'The number of days old an issue can be before marking it stale'
    default: 60
  days-before-close:
    description: 'The number of days to wait to close an issue or pull request after it being marked stale'
    default: 7
  stale-issue-label:
    description: 'The label to apply when an issue is stale'
    default: 'Stale'
  exempt-issue-label:
    description: 'The label to apply when an issue is exempt from being marked stale'
  stale-pr-label:
    description: 'The label to apply when a pull request is stale'
    default: 'Stale'
  exempt-pr-label:
    description: 'The label to apply when a pull request is exempt from being marked stale'
  operations-per-run:
    description: 'The maximum number of operations per run, used to control rate limiting'
    default: 30
  ignore-issues:
    description: 'Ignore issues when searching for stale items'
    default: false
  ignore-prs:
    description: 'Ignore pull requests when searching for stale items'
    default: false
runs:
  using: 'node12'
  main: 'lib/main.js'
